"""empty message

Revision ID: a2bd78b6b62e
Revises: 02215d30b850
Create Date: 2022-08-06 09:13:57.861762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2bd78b6b62e'
down_revision = '02215d30b850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image', sa.String(length=250), nullable=True))
    op.alter_column('recipes', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=5000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('categories', 'image')
    # ### end Alembic commands ###
