"""empty message

Revision ID: c0feb8b9785d
Revises: 890e56d4cae1
Create Date: 2022-08-19 15:15:20.757641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0feb8b9785d'
down_revision = '890e56d4cae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'user_id')
    # ### end Alembic commands ###
