"""empty message

Revision ID: e7b2b92caad7
Revises: b5938ac8f0db
Create Date: 2022-08-02 09:02:18.733863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b2b92caad7'
down_revision = 'b5938ac8f0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('image', sa.String(length=250), nullable=True))
    op.add_column('recipes', sa.Column('image', sa.String(length=250), nullable=True))
    op.add_column('trivia', sa.Column('image', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trivia', 'image')
    op.drop_column('recipes', 'image')
    op.drop_column('ingredients', 'image')
    # ### end Alembic commands ###